version: "3.3"
services:
  csvserver:
    image: infracloudio/csvserver
    container_name: "csvserver"
    volumes:
      - ${PWD}/inputdata:/csvserver/inputdata
    ports:
      - 9393:9300
    env_file:
      - csvserver.env
  

